### ISSUE TITLE
plugin/extension couldn't be installed in VSCode Remote SSH instance/environment

### ISSUE THREAD

**Issue by RUVATA** [mxsdev/ts-type-explorer#51]
Trying to install this plugin/extension on Remote SSH VSCode instance/environment - freezes on "Installing" step, and never be endeded, if target host could't have free acccess to web;

`Error while installing 'mxsdev.typescript-explorer' extension in the remote server. connect EACCES 64:ff9b::d6b:6af:443`

Many other plugins do not have such a need/need when installing, getting everything they need from the user host 🤷‍♂️
May be possible to include dependency in package of plugin?

```shell
2024-04-08 15:15:39.491 [info] Started local extension host with pid 75330.
2024-04-08 15:15:39.680 [info] Invoking resolveAuthority(ssh-remote)...
2024-04-08 15:15:39.680 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2024-04-08 15:15:39.681 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2024-04-08 15:15:39.796 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][115ms] returned Managed(1)
2024-04-08 15:15:39.796 [info] resolveAuthority(ssh-remote) returned 'Managed(1)' after 115 ms
2024-04-08 15:15:39.796 [info] Creating a socket (renderer-Management-ffbbb26e-8e6e-41b4-b274-c3e5ffaca6ad)...
2024-04-08 15:15:39.796 [info] Creating a socket (renderer-ExtensionHost-1ec1bb1e-86d2-4222-b96a-565893d3b5e6)...
2024-04-08 15:15:39.834 [info] Creating a socket (renderer-ExtensionHost-1ec1bb1e-86d2-4222-b96a-565893d3b5e6) was successful after 38 ms.
2024-04-08 15:15:39.835 [info] Creating a socket (renderer-Management-ffbbb26e-8e6e-41b4-b274-c3e5ffaca6ad) was successful after 39 ms.
2024-04-08 15:15:43.076 [info] [perf] Render performance baseline is 18ms
2024-04-08 15:15:45.066 [info] Extension host (Remote) is unresponsive.
2024-04-08 15:15:47.091 [info] Extension host (Remote) is responsive.
2024-04-08 15:20:57.899 [error] Unable to resolve resource search-editor:#0.10431004774635366: Error: Unable to resolve resource search-editor:#0.10431004774635366
    at a.r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2412:25870)
    at a.r (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2412:25856)
    at async C.acquire (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:37:3392)
    at async u.createModelReference (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:2412:27205)
    at async a (vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:769:76506)
2024-04-08 17:51:15.404 [error] Error while installing 'mxsdev.typescript-explorer' extension in the remote server. connect EACCES 64:ff9b::d6b:6af:443
2024-04-08 17:51:15.406 [info] Downloading the 'mxsdev.typescript-explorer' extension locally and install
2024-04-08 17:51:17.087 [info] Downloaded extension: mxsdev.typescript-explorer /Users/ruvata34/Library/Application Support/Code/CachedExtensionVSIXs/mxsdev.typescript-explorer-0.4.2
2024-04-08 18:06:24.063 [info] Started local extension host with pid 79850.
2024-04-08 18:06:24.271 [info] Invoking resolveAuthority(ssh-remote)...
2024-04-08 18:06:24.271 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] obtaining proxy...
2024-04-08 18:06:24.272 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][0ms] invoking...
2024-04-08 18:06:24.385 [info] [LocalProcess0][resolveAuthority(ssh-remote,1)][114ms] returned Managed(1)
2024-04-08 18:06:24.385 [info] resolveAuthority(ssh-remote) returned 'Managed(1)' after 114 ms
2024-04-08 18:06:24.386 [info] Creating a socket (renderer-Management-efb01497-b662-4749-b71c-8c3bc26793e2)...
2024-04-08 18:06:24.386 [info] Creating a socket (renderer-ExtensionHost-1af97ced-73e4-4a23-8d3c-2cc13b885d30)...
2024-04-08 18:06:24.428 [info] Creating a socket (renderer-Management-efb01497-b662-4749-b71c-8c3bc26793e2) was successful after 42 ms.
2024-04-08 18:06:24.429 [info] Creating a socket (renderer-ExtensionHost-1af97ced-73e4-4a23-8d3c-2cc13b885d30) was successful after 43 ms.
2024-04-08 18:06:27.416 [info] [perf] Render performance baseline is 16ms
2024-04-08 18:06:29.674 [info] Extension host (Remote) is unresponsive.
2024-04-08 18:06:31.041 [info] Extension host (Remote) is responsive.
2024-04-08 18:07:27.872 [error] Error while installing 'mxsdev.typescript-explorer' extension in the remote server. connect EACCES 64:ff9b::d6b:6af:443
```

**Comment by RUVATA** [comment]
successfully works at latest versions of VSCode remote server
(over version: 1.89.1)
